[tool.ruff]
target-version = "py311"
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D",       # pydocstring
    "ANN",     # type annotations
    "COM812",  # trailing comma (conflicts with formatter)
    "ISC001",  # implicit string concat (conflicts with formatter)
    "PLR0913", # too many arguments
    "ERA001",  # commented-out code
    "S324",    # md5 for checksums not crypto
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"tgdigest/tests.py" = ["S101", "RUF001", "E501", "SLF001", "W293"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
line-ending = "auto"

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"