target-version = "py311"

[lint]
select = ["ALL"]
ignore = [
    "D",      # pydocstring
    "ANN",    # type annotations
    "COM812", # trailing comma (conflicts with formatter)
    "ISC001", # implicit string concat (conflicts with formatter)
]

[lint.per-file-ignores]
"__init__.py" = ["F401"]

[format]
quote-style = "single"
indent-style = "space"
line-ending = "auto"