category_slug: requirements
questions_text_md5: 7fe8158ac038171d4bd18e597f01290e
questions:
- normalized_question: Какая минимальная сумма покрытия страховки требуется для получения
    шенгенской визы?
  source_questions:
  - В каких страховых компаниях можно получить страховку с суммой покрытия не менее
    100000 евро?
  - Какая сумма покрытия страховки должна быть для получения визы во Францию и другие
    страны Шенгена?
  - Какое минимальное покрытие должно быть у страховки для шенгенской визы при наличии
    российского паспорта?
- normalized_question: Нужно ли включать покрытие COVID-19 в страховку для получения
    шенгенской визы?
  source_questions:
  - Какие посольства требуют явное указание COVID в страховке?
  - Можно ли исключать страховку от COVID-19 из полиса Dunav при подаче на Шенген?
  - Нужна ли страховка от пандемии для шенгенской визы при покупке полиса Дунав?
  - Нужно ли включать опцию Ковид при оформлении страховки Дунав для Шенгена?
  - Обязательно ли включать ковид в страховку для получения визы?
- normalized_question: Какую страховку и на какой срок нужно оформлять для получения
    многократной шенгенской визы?
  source_questions:
  - Достаточно ли при подаче на многократную визу предоставить страховку только под
    первую поездку?
  - Какую страховку делать для получения мультивизы Шенген на полгода или год?
  - Какую страховку нужно делать для многократной шенгенской визы в Испанию и на какой
    срок?
  - Можно ли для мультивизы делать страховку только на первый въезд, а затем для фактических
    въездов?
  - Можно ли купить короткую страховку на 8 дней для получения мультивизы в Италию
    или обязательно нужна длинная страховка?
  - Можно ли получить годовую мультивизу, если страховка оформлена только на 90 дней?
  - Нужно ли покупать страховку на больше чем 30 дней, чтобы получить визу на несколько
    месяцев?
- normalized_question: Подходит ли страховка от Дунав (Dunav) для получения шенгенской
    визы?
  source_questions:
  - Можно ли использовать карту Дунав (бонус при открытии бизнес-счета в Поштанске)
    в качестве страховки для подачи на Шенген?
  - Можно ли использовать страховку Дунав для ВНЖ в Сербии для подачи на шенген?
  - Подойдет ли страховка Dunav для боравка (для получения ВНЖ) для подачи на шенгенскую
    визу?
  - Подходит ли страховка Дунав для венгерского шенгена?
  - Подходит ли страховка от Дунава и Поштанске (которую выдают при открытии бизнес-счета)
    для получения визы в Шенген?
  - Принимают ли страховки от Дунав без печати и подписи в документе «Подтверда» для
    шенгенской визы?
- normalized_question: Подходит ли сербская медицинская страховка (здравствена картица/ОМС)
    для получения шенгенской визы или поездки в Шенген?
  source_questions:
  - Можно ли использовать сербскую здравствену картицу (медицинскую карту) вместо
    туристической страховки для поездки в Шенген?
  - Подходит ли государственная страховка здоровья (для владельцев ВНЖ) для поездок
    в шенген?
  - Подходит ли обычное сербское здравственное страхование (zdravstveno osiguranje)
    в качестве туристической страховки для поездки в Хорватию?
  - Подходит ли сербская или черногорская медицинская страховка (ОМС) для подачи на
    визу в Испанию?
  - Подходит ли сербская страховка (типа ОМС) для получения визы Шенген?
- normalized_question: Подходит ли страховка от Райффайзен банка (Raiffeisen Premium/Uniqa)
    для получения шенгенской визы?
  source_questions:
  - Какие документы нужно прикладывать при подаче на шенген со страховкой Raiffeisen
    Premium (Uniqa)?
  - Можно ли использовать страховку от Райффайзен банка Сербии для получения визы?
  - Подходит ли страховка Райффайзен банка (Raif Premium) для шенгенской визы?
  - Покрывает ли страховка Райф-Премиум риски COVID-19 для посольств?
- normalized_question: Подходит ли страховка Generali для получения шенгенской визы
    и нужно ли её переводить?
  source_questions:
  - Подойдет ли ДМС Generali в качестве страховки для получения шенгенских виз?
  - Покрывает ли страховка Generali лечение COVID-19?
  - Принимают ли страховку Generali при подаче на визу? Нужно ли переводить её на
    английский? Нормально ли, что сумма покрытия не указана в полисе?
- normalized_question: Подходит ли страховка Safety Wing (SafetyWing) для получения
    шенгенской визы?
  source_questions:
  - Принимают ли американскую страховку SafetyWing для визы в Германию?
  - Принимают ли в Венгрии страховку Safety Wings или Genki для получения визы?
- normalized_question: Подходит ли страховка Genki для получения шенгенской визы?
  source_questions:
  - Подходит ли страховка Genki для испанского шенгена?
  - Принимают ли в Венгрии страховку Safety Wings или Genki для получения визы?
- normalized_question: Нужно ли переводить сербскую страховку на английский язык для
    подачи на визу?
  source_questions:
  - Нужна ли сербская страховка для подачи на визу в Сербии и нужно ли её переводить?
  - Нужно ли переводить сербскую страховку на английский для посольства?
- normalized_question: Какие документы/страницы из страхового полиса нужно прикладывать
    при подаче на визу?
  source_questions:
  - Какие страницы из страхового полиса нужно прикладывать к документам для визы?
  - Что нужно распечатать из страхового полиса для посольства, если страховая компания
    прислала файл на 44 страницы (например, Generali)?
- normalized_question: Нужно ли распечатывать страховку для подачи на визу или достаточно
    электронного варианта?
  source_questions:
  - Достаточно ли иметь на руках договор страховки путешественника, оформленной онлайн,
    или нужны какие-то ламинированные карточки?
  - Нужно ли распечатывать страховку для подачи на визу?
- normalized_question: Подходит ли страховка, которая идет бонусом к банковской карте
    (Mastercard Gold, Поштанска), для получения шенгенской визы?
  source_questions:
  - Одобряют ли в посольстве Венгрии страховку от Поштански (которая идет с бизнес
    счетом) - достаточно ли копии пластиковой карты?
  - Подходит ли страховка от Мастеркард Голд для визы?
  - Подходит ли страховка от банка (которая идет бонусом к карте) для шенгенской визы?
- normalized_question: Принимают ли консульства российские страховые компании (Тинькофф,
    Черехапа) для оформления шенгенской визы?
  source_questions:
  - Какие консульства в Белграде принимают российскую страховку (Тинькофф или Черехапа)
    для оформления шенгенской визы?
  - Если виза выдана с российской страховкой, значит ли это, что со страховкой всё
    в порядке?
