category_slug: requirements
questions_text_md5: 79ba53416872f048f80edf8f21ec5986
questions:
- normalized_question: Какую страховую компанию выбрать для получения шенгенской визы?
  source_questions:
  - В каких страховых компаниях можно получить страховку с суммой покрытия не менее
    100000 евро?
  - Какую страховку порекомендуете для получения шенгенской визы?
  - Какую страховую компанию выбрать для получения визы Д Сербии?
- normalized_question: Какая сумма покрытия страховки требуется для получения шенгенской
    визы?
  source_questions:
  - Какая сумма покрытия страховки должна быть для получения визы во Францию и другие
    страны Шенгена?
  - Какое минимальное покрытие должно быть у страховки для шенгенской визы при наличии
    российского паспорта?
- normalized_question: Какую страховку нужно делать для получения мультивизы Шенген?
  source_questions:
  - Какую страховку делать для получения мультивизы Шенген на полгода или год?
  - Какую страховку нужно делать для многократной шенгенской визы в Испанию и на какой
    срок?
- normalized_question: Достаточно ли при подаче на многократную визу предоставить
    страховку только на первую поездку?
  source_questions:
  - Достаточно ли при подаче на многократную визу предоставить страховку только под
    первую поездку?
  - Можно ли для мультивизы делать страховку только на первый въезд, а затем для фактических
    въездов?
  - Можно ли купить короткую страховку на 8 дней для получения мультивизы в Италию
    или обязательно нужна длинная страховка?
- normalized_question: Можно ли получить годовую мультивизу, если страховка оформлена
    только на 90 дней?
  source_questions:
  - Можно ли получить годовую мультивизу, если страховка оформлена только на 90 дней?
  - Нужно ли покупать страховку на больше чем 30 дней, чтобы получить визу на несколько
    месяцев?
- normalized_question: Как работает годовая страховка с ограниченным количеством дней
    покрытия?
  source_questions:
  - Как работает годовая страховка с покрытием 30 дней - это 30 дней суммарно за год
    или 30 дней на каждую поездку?
  - Как работает покрытие страховки на 3 года с 90 днями в каждые 365 дней?
  - Принимают ли консульства годовую страховку с ограниченным количеством дней пребывания?
- normalized_question: Обязательно ли включать COVID-19 в страховку для получения
    шенгенской визы?
  source_questions:
  - Какие посольства требуют явное указание COVID в страховке?
  - Можно ли исключать страховку от COVID-19 из полиса Dunav при подаче на Шенген?
  - Нужна ли страховка от пандемии для шенгенской визы при покупке полиса Дунав?
  - Нужно ли включать опцию Ковид при оформлении страховки Дунав для Шенгена?
  - Обязательно ли включать ковид в страховку для получения визы?
  - Покрывает ли страховка Generali лечение COVID-19?
  - Покрывает ли страховка Райф-Премиум риски COVID-19 для посольств?
- normalized_question: Нужно ли переводить сербскую страховку на английский язык для
    подачи на визу?
  source_questions:
  - Нужна ли сербская страховка для подачи на визу в Сербии и нужно ли её переводить?
  - Нужно ли переводить сербскую страховку на английский для посольства?
  - Принимают ли страховку Generali при подаче на визу? Нужно ли переводить её на
    английский? Нормально ли, что сумма покрытия не указана в полисе?
- normalized_question: Какие страницы из страхового полиса нужно прикладывать к документам
    для визы?
  source_questions:
  - Какие страницы из страхового полиса нужно прикладывать к документам для визы?
  - Что нужно распечатать из страхового полиса для посольства, если страховая компания
    прислала файл на 44 страницы (например, Generali)?
- normalized_question: Нужно ли распечатывать страховку для подачи на визу или достаточно
    электронного варианта?
  source_questions:
  - Достаточно ли иметь на руках договор страховки путешественника, оформленной онлайн,
    или нужны какие-то ламинированные карточки?
  - Нужно ли распечатывать страховку для подачи на визу?
- normalized_question: Подходит ли сербская медицинская страховка (zdravstveno osiguranje)
    для получения шенгенской визы?
  source_questions:
  - Можно ли использовать сербскую здравствену картицу (медицинскую карту) вместо
    туристической страховки для поездки в Шенген?
  - Подходит ли государственная страховка здоровья (для владельцев ВНЖ) для поездок
    в шенген?
  - Подходит ли обычное сербское здравственное страхование (zdravstveno osiguranje)
    в качестве туристической страховки для поездки в Хорватию?
  - Подходит ли сербская или черногорская медицинская страховка (ОМС) для подачи на
    визу в Испанию?
  - Подходит ли сербская страховка (типа ОМС) для получения визы Шенген?
- normalized_question: Подходит ли страховка Dunav для получения шенгенской визы?
  source_questions:
  - Можно ли использовать карту Дунав (бонус при открытии бизнес-счета в Поштанске)
    в качестве страховки для подачи на Шенген?
  - Можно ли использовать страховку Дунав для ВНЖ в Сербии для подачи на шенген?
  - Подойдет ли страховка Dunav для боравка (для получения ВНЖ) для подачи на шенгенскую
    визу?
  - Подходит ли страховка Дунав для венгерского шенгена?
  - Подходит ли страховка от Дунава и Поштанске (которую выдают при открытии бизнес-счета)
    для получения визы в Шенген?
  - Принимают ли страховки от Дунав без печати и подписи в документе «Подтверда» для
    шенгенской визы?
- normalized_question: Подходит ли страховка Raiffeisen Premium (Uniqa) для получения
    шенгенской визы?
  source_questions:
  - Какие документы нужно прикладывать при подаче на шенген со страховкой Raiffeisen
    Premium (Uniqa)?
  - Можно ли использовать страховку от Райффайзен банка Сербии для получения визы?
  - Подходит ли страховка Райффайзен банка (Raif Premium) для шенгенской визы?
- normalized_question: Подходит ли страховка Generali для получения шенгенской визы?
  source_questions:
  - Подойдет ли ДМС Generali в качестве страховки для получения шенгенских виз?
  - Принимают ли страховку Generali при подаче на визу? Нужно ли переводить её на
    английский? Нормально ли, что сумма покрытия не указана в полисе?
- normalized_question: Подходит ли страховка Safety Wings (SafetyWing) для получения
    шенгенской визы?
  source_questions:
  - Принимают ли американскую страховку SafetyWing для визы в Германию?
  - Принимают ли в Венгрии страховку Safety Wings или Genki для получения визы?
- normalized_question: Подходит ли страховка Genki для получения шенгенской визы?
  source_questions:
  - Подходит ли страховка Genki для испанского шенгена?
  - Принимают ли в Венгрии страховку Safety Wings или Genki для получения визы?
- normalized_question: Подходит ли страховка от банка (бонусная к карте) для получения
    шенгенской визы?
  source_questions:
  - Подходит ли страховка от Мастеркард Голд для визы?
  - Подходит ли страховка от банка (которая идет бонусом к карте) для шенгенской визы?
- normalized_question: Подходит ли страховка от Поштанске (которая идет с бизнес счетом)
    для получения визы в Венгрию?
  source_questions:
  - Одобряют ли в посольстве Венгрии страховку от Поштански (которая идет с бизнес
    счетом) - достаточно ли копии пластиковой карты?
  - Подходит ли страховка от Дунава и Поштанске (которую выдают при открытии бизнес-счета)
    для получения визы в Шенген?
- normalized_question: Должен ли указываться номер паспорта в страховке и имеет ли
    это значение для визы и пограничного контроля?
  source_questions:
  - Должен ли указываться номер паспорта в страховке и имеет ли это значение для пограничника?
  - Критично ли отсутствие номера паспорта в страховке для пограничников при первом
    въезде в Шенген (Швеция), если есть только фамилия, имя, номер полиса и персональный
    код страны ЕС?
- normalized_question: Нормально ли для шенгенской визы, что в страховке указано worldwide
    вместо конкретно Шенгенская зона?
  source_questions:
  - Нормально ли для шенгенской визы, что в страховке указано worldwide, а не конкретно
    Шенгенская зона?
  - Принимают ли при подаче на итальянский Шенген разовую туристическую страховку
    от Wiener только на Италию, если в требованиях написано про покрытие всей территории
    стран-членов?
