baseURL = 'https://tgdigest.github.io/serbia-visas-for-other-countries/'
languageCode = 'ru'
defaultContentLanguage = 'ru'
title = 'Визы из Сербии'

[services.googleAnalytics]
ID = "G-5HFLQ7ZT20"

[module]
  [[module.imports]]
    path = 'github.com/imfing/hextra'

[languages.ru]
languageName = 'Русский'
weight = 1
