category_slug: requirements
questions_text_md5: a01fd4db872e8b0e2d765c0591a3501c
questions:
- normalized_question: Берут ли консульский сбор за детей до 6 лет?
  source_questions:
  - Берут ли консульский сбор за детей до 6 лет?
  - Освобождены ли дети от визового сбора?
- normalized_question: Как оплачивается консульский сбор в консульстве Венгрии (наличные/карта,
    евро/динары)?
  source_questions:
  - В каком формате оплата сбора в консульстве Венгрии в Субботице?
  - В чем оплачивается пошлина на визу в посольстве - евро или динары?
  - Как оплачивается визовый сбор в венгерском консульстве?
  - Как оплачивается визовый сбор?
  - Как оплачивается консульский сбор в Суботице - картой или наличными?
  - Как оплачивается консульский сбор?
  - Как оплачивается пошлина в Суботице?
  - Как оплачивать визовый сбор в консульстве Венгрии в Белграде - можно ли в динарах?
  - Как оплачивать визовый сбор в консульстве?
  - Как оплачивать визовый сбор?
  - Как оплачивать консульские сборы в консульстве Венгрии - картой или наличными,
    в динарах или евро?
  - Как оплачивать консульский сбор?
  - Какая оплата визового сбора в консульстве - наличные или карта?
  - Какой визовый сбор и как его оплатить?
  - Можно ли оплатить визовый сбор динарами или нужны евро?
  - Можно ли оплатить визовый сбор картой в посольстве?
  - Нужно ли оплачивать визовый сбор до приема в консульстве или во время приема?
  - Когда платить за визу - при подаче или при получении?
- normalized_question: Возвращается ли визовый сбор в случае отказа в визе?
  source_questions:
  - Возвращается ли визовый сбор в случае отказа в визе?
- normalized_question: Какая стоимость консульского сбора за венгерскую визу?
  source_questions:
  - Какая пошлина за венгерскую визу и в какой валюте оплачивается?
  - Какая пошлина за визу в Венгрию?
  - Какая пошлина за визу для граждан Беларуси?
  - Какая стоимость визы в Венгрию для граждан России?
  - Сколько стоит виза в Венгрию для взрослого?
  - Сколько стоит визовый сбор и как его оплачивать?
  - Сколько стоит консульский сбор и как его оплачивать?
  - Сколько стоит консульский сбор и можно ли оплатить картой?
- normalized_question: Где купить медицинскую страховку для визы в Венгрию?
  source_questions:
  - Где делать страховку для визы в Венгрию?
  - Где купить медицинскую страховку для визы?
  - Где купить страховку для венгерской визы?
  - Где можно купить страховку для визы в Венгрию онлайн в Сербии?
  - Где можно оформить годовую страховку для визы и сколько она стоит?
  - Где можно сделать страховку онлайн для визы в Венгрию?
- normalized_question: Какая страховка нужна для визы в Венгрию и какие требования
    к ней?
  source_questions:
  - Какая страховка нужна для визы?
  - Какая страховка требуется для поездки в Венгрию?
  - Какая сумма покрытия страховки должна быть для венгерской визы?
  - Какие страховки принимают для венгерской визы?
  - Какие страховки принимают для визы в Венгрию?
  - Какие требования к страховке для визы в Венгрию? Принимают ли страховку Тинькофф?
  - Какое покрытие должно быть у страховки для венгерской визы?
  - Какую медицинскую страховку нужно оформить для поездки в Венгрию?
  - Какую страховку лучше оформить для визы в Венгрию?
  - Какую страховку нужно делать для венгерской визы? Подходят ли российские страховки
    (Альфа, Тинькофф)?
  - Какую страховку принимают для венгерской визы?
  - Какую страховку принимают для визы в Венгрию?
  - Какую страховку принимают для визы?
  - Какую сумму покрытия требуют для медицинской страховки на визу в Венгрию?
  - Нужна ли медицинская страховка для венгерской визы и какие требования?
  - Нужна ли медицинская страховка и какое покрытие?
  - Нужна ли страховка для подачи на венгерскую визу?
  - Нужна ли страховка для подачи на визу в Венгрию, если есть сербский ОМС?
  - Нужна ли страховка для подачи на визу и на какую сумму?
  - Требования к страховке для венгерской визы такие же как в России?
  - Требуется ли медицинская страховка для подачи на визу в Венгрию?
- normalized_question: Можно ли использовать российскую страховку для визы в Венгрию?
  source_questions:
  - Можно ли использовать российскую страховку для визы в Венгрию?
  - Нужна ли страховка из российской компании?
  - Подойдет ли русская страховка для оформления визы в Венгрию?
  - Принимают ли страховые полисы из России для венгерской визы?
- normalized_question: Подходит ли сербский ОМС (здравствена книжица) как страховка
    для визы в Венгрию?
  source_questions:
  - Можно ли использовать сербскую здравственну картицу вместо платной страховки?
  - Подойдет ли здравствена книжица (полученная с ВНЖ) для визы в Венгрию?
  - Подходит ли сербский ОМС как страховка для получения шенгенской визы?
- normalized_question: Какую страховку нужно покупать при запросе мультивизы?
  source_questions:
  - Какую страховку купить на визу D (годовую) с пребыванием до 90 дней, чтобы полис
    был на английском?
  - Какую страховку нужно покупать при запросе мультивизы?
  - Нужно ли покупать страховку на весь период мультивизы или достаточно под первую
    поездку?
- normalized_question: Нужны ли печати на страховке для визы в Венгрию?
  source_questions:
  - Нужны ли печати на страховке для визы в Венгрию?
- normalized_question: Дают ли визу по небиометрическому паспорту старого образца?
  source_questions:
  - Дают ли визу по пятилетнему (небиометрическому) паспорту?
  - Может ли ребенок до года подаваться на венгерский шенген с 5-летним загранпаспортом?
  - Можно ли подать на визу с паспортом без биометрии (старого образца)?
  - Принимают ли с небиометрическим паспортом?
- normalized_question: Какие требования к сроку действия ВНЖ для подачи на визу в
    Венгрию?
  source_questions:
  - Есть ли у Венгрии правило о минимальном сроке действия сербского ВНЖ для подачи
    на визу?
  - За сколько месяцев до окончания боровака принимают документы на визу в Венгрию?
  - Имеет ли смысл подаваться на визу если боравак истекает через полтора месяца?
  - Какие сроки по ВНЖ должны быть для подачи на шенген в Венгрию?
  - Какие требования к ВНЖ для подачи на визу?
  - Какие требования к ВНЖ для получения венгерской визы?
  - Какие требования к сроку действия ВНЖ после окончания поездки?
  - Какие требования к сроку действия ВНЖ при подаче на визу?
  - Какие требования к сроку действия боравака (ВНЖ) для подачи на визу?
  - Критично ли, если ВНЖ заканчивается менее чем через 3 месяца после планируемой
    поездки?
  - Можно ли подаваться на визу если ВНЖ заканчивается через 2 месяца?
  - Можно ли подаваться на визу, если ВНЖ заканчивается менее чем через 3 месяца после
    поездки?
  - Можно ли подаваться на визу, если ВНЖ заканчивается через несколько месяцев?
  - Можно ли подаваться на визу, если ВНЖ истекает менее чем через 3 месяца?
  - Можно ли подать документы на визу, если ВНЖ заканчивается менее чем через 3 месяца
    после планируемой поездки?
  - Насколько требовательно консульство к тому, чтобы ВНЖ Сербии действовал еще не
    менее 3 месяцев после даты выезда из Шенгена?
  - Требуется ли, чтобы ВНЖ был действителен еще 6 месяцев с момента въезда для получения
    венгерской визы?
  - Требуют ли венгры 6 месяцев боравака для подачи на визу?
  - Что делать, если от конца поездки до окончания боравака остается меньше 3 месяцев?
- normalized_question: Можно ли подаваться на визу в Венгрию сразу после получения
    сербского ВНЖ?
  source_questions:
  - Дают ли визу со свежим бороваком (полученным недавно)?
  - Есть ли статистика по тому, сколько должно пройти времени между получением ВНЖ
    и подачей на визу в Венгрию? Были ли отказы из-за того, что прошло мало времени?
  - Можно ли подавать на визу в Венгрию сразу после получения сербского ВНЖ?
  - Можно ли подавать на визу в Венгрию со свежим ВНЖ?
  - Можно ли подаваться на визу сразу после получения ВНЖ в Сербии?
  - Можно ли подаваться на визу сразу после получения ВНЖ или нужно ждать?
  - Можно ли подаваться на визу сразу после получения ВНЖ?
  - Можно ли подаваться на шенген, если сделал боровак примерно месяц назад?
  - Нужно ли ждать 6 месяцев после получения второго боровака перед подачей на визу?
  - Нужно ли ждать определенный срок после получения боравака перед подачей на визу
    в Венгрию?
  - Через сколько времени от получения ВНЖ Сербии можно подаваться на венгерский шенген?
- normalized_question: Можно ли подаваться на визу, если ВНЖ находится в процессе
    продления?
  source_questions:
  - Можно ли записаться на визу, если Боравак скоро заканчивается, а новый не выдали?
  - Можно ли подавать заявку на прием в посольство, если боровак заканчивается раньше
    даты подачи, но уже подано заявление на продление?
  - Можно ли подаваться на визу с ВНЖ, который находится в процессе продления?
  - Можно ли подаваться на визу, если ВНЖ заканчивается и подано на продление?
  - Можно ли подать на визу в Венгрию с истекающим ВНЖ и подтверждением о продлении?
  - Что делать если истек ВНЖ в Сербии, а новый еще не готов - можно ли подаваться
    на венгерскую визу?
  - Что делать, если ВНЖ заканчивается раньше, чем планируемая поездка?
- normalized_question: Можно ли подать документы на визу в Венгрию после одобрения
    ВНЖ, но до получения пластиковой карты?
  source_questions:
  - Можно ли подать документы на венгерскую визу после того как сербский ВНЖ approved,
    но пластиковая карта еще не готова?
  - Можно ли подать на визу в паспорт без налепницы, если есть пластиковая ID карта
    ВНЖ?
- normalized_question: Можно ли подаваться на визу в Венгрию без ВНЖ Сербии?
  source_questions:
  - Можно ли подаваться на White Card без ВНЖ в Сербии?
  - Можно ли подаваться на венгерскую визу без ВНЖ в Сербии?
  - Можно ли подаваться на рабочую визу в Венгрию в Сербии без ВНЖ Сербии?
  - Можно ли подаваться на транзитную визу Венгрии с белым картоном без ВНЖ?
  - Можно ли подаваться на туристическую визу в Венгрию без ВНЖ Сербии?
  - Можно ли подать документы на визу в Венгрию без ВНЖ Сербии?
  - Можно ли получить транзитную визу Венгрии для проезда в Великобританию без сербского
    ВНЖ?
  - Нужен ли ВНЖ Сербии для подачи на национальную (рабочую) визу Венгрии?
- normalized_question: Можно ли получить визу в Венгрию без официального трудоустройства
    в Сербии?
  source_questions:
  - Возможно ли получить визу в Венгрию без трудового договора при ВНЖ по таланту?
  - Есть ли шанс получить туристическую визу в Венгрию без ИП/трудоустройства при
    ВНЖ по недвижимости?
  - Какие шансы получить визу без местной работы в Сербии?
  - Можно ли подаваться на венгерскую визу как безработный?
  - Можно ли подаваться на венгерскую визу с ИП без оборотов или с замороженным ИП?
  - Можно ли подаваться на визу без официального трудоустройства в Сербии?
  - Можно ли подаваться на визу без работы в Сербии (безработным)?
  - Можно ли подать на визу с ВНЖ по недвижимости и работой на российскую компанию?
  - Можно ли подать на визу с ВНЖ по таланту без ИП и работы?
  - Можно ли подать на визу с работой в российской компании без трудоустройства в
    Сербии?
  - Можно ли подать на визу, если ВНЖ по фирме-нулевке, а деньги получаю в крипте?
  - Можно ли получить венгерскую визу без официального трудоустройства в Сербии?
  - Можно ли получить венгерскую визу без работы в Сербии, только с недвижимостью?
  - Можно ли получить венгерскую визу с ВНЖ по недвижимости без официальной работы?
  - Можно ли получить венгерскую визу с ВНЖ по таланту без официального дохода в Сербии?
  - Можно ли получить визу без работы, но с деньгами на счету?
  - Можно ли получить визу в Венгрию студенту-безработному с ВНЖ по таланту без официальной
    работы?
  - Можно ли получить визу с ВНЖ по воссоединению семьи без работы?
  - Можно ли получить визу с российским ИП и доходом там же, но с сербским ВНЖ?
  - Нужен ли трудовой договор для получения визы в Венгрию?
  - Что делать, если работаешь не на сербского работодателя?
- normalized_question: Можно ли подаваться на визу с недавно открытым ИП?
  source_questions:
  - Можно ли подаваться на визу с недавно открытым ИП (меньше месяца)?
- normalized_question: Можно ли подаваться на визу с трудовым договором на part time?
  source_questions:
  - Можно ли подаваться на визу с трудовым договором на part time (частичную занятость)?
- normalized_question: Какая минимальная сумма денег на счету должна быть для получения
    венгерской визы?
  source_questions:
  - Какая минимальная сумма денег на счету должна быть на человека в день для получения
    венгерской визы?
  - Какая минимальная сумма должна быть на счете для получения визы?
  - Какой минимальный баланс на счету нужен для одобрения визы?
  - Какой минимальный остаток должен быть на счету для подачи на туристическую визу?
  - Какой остаток на счете нужен для поездки на 5-6 дней?
  - Какую сумму денег нужно показать на счете для получения визы?
  - Сколько должно быть денег на счету на двоих для визы в Венгрию?
  - Сколько примерно требуется евро в день на счету для одобрения визы?
- normalized_question: Какие требования к фотографии для венгерской визы?
  source_questions:
  - Должны ли фотографии на визу быть матовыми?
  - Какие требования к фото на визу?
  - Какие требования к фотографии для венгерской визы?
  - Какой размер фото нужен для венгерской визы?
  - 'Какой размер фото нужен для визы: 3х4 или 3,5х4,5?'
  - Какой размер фотографии нужен для визы?
  - Принимают ли фото с серым фоном?
  - Сколько фотографий нужно для подачи на визу?
- normalized_question: Нужно ли новое фото при повторной подаче на визу?
  source_questions:
  - Нужно ли новое фото при повторной подаче на визу через 2 месяца после предыдущей?
- normalized_question: Можно ли подавать документы на визу в Венгрию, если планируется
    поездка в несколько стран Шенгена?
  source_questions:
  - Можно ли подавать документы на визу в Венгрию, если планируется поездка не только
    в Венгрию, но и в другие страны Шенгена?
  - Какие требования к маршруту поездки для получения венгерской визы?
- normalized_question: Можно ли подаваться на визу с двумя загранпаспортами РФ?
  source_questions:
  - Можно ли подаваться на визу с двумя загранпаспортами РФ?
  - Что делать если есть два паспорта РФ?
- normalized_question: Что делать, если ВНЖ вклеен в старый недействующий паспорт?
  source_questions:
  - Принимают ли в консульстве Венгрии паспорт с новым номером, если ВНЖ вклеен в
    старый паспорт?
  - Что делать если ВНЖ в старом недействующем паспорте?
- normalized_question: Можно ли оформить визу без договора аренды квартиры?
  source_questions:
  - Можно ли оформить визу без договора аренды квартиры?
- normalized_question: Какая страховка нужна на автомобиль для поездки в Венгрию?
  source_questions:
  - Как оформить страховку для авто с российскими номерами для поездки в Венгрию?
  - Какая страховка нужна на машину, купленную в Сербии, для поездки в Венгрию?
  - Нужна ли страховка на автомобиль при подаче документов на визу, если планируется
    поездка на машине?
  - Нужна ли страховка на машину при подаче на визу?
- normalized_question: Влияют ли визы, полученные в России, на получение визы в Сербии?
  source_questions:
  - Влияют ли визы, полученные в России, на получение визы в Сербии?
  - Какая визовая история нужна для подачи на венгерскую визу?
- normalized_question: Можно ли подаваться на визу в Венгрию в России, если есть сербский
    ВНЖ?
  source_questions:
  - Можно ли использовать страховку, оформленную в Сербии, при подаче на визу из России?
  - Можно ли подаваться на визу в Венгрию в России, если есть сербский ВНЖ?
- normalized_question: Дают ли шенген с ВНЖ по учебе?
  source_questions:
  - Дают ли шенген с ВНЖ по учебе?
- normalized_question: Можно ли подаваться на визу в Венгрию с ВНЖ на 4 месяца?
  source_questions:
  - Можно ли подаваться на визу в Венгрию с внж на 4 месяца?
- normalized_question: Можно ли подаваться на визу с супругом, если у супруга нет
    ВНЖ?
  source_questions:
  - Можно ли подаваться на визу с супругом, если у супруга нет документов (ВНЖ)?
- normalized_question: Можно ли подаваться на туристическую визу в Венгрию, пока рассматривается
    заявка на визу D?
  source_questions:
  - Можно ли подаваться на туристическую визу в Венгрию, пока рассматривается заявка
    на визу D?
- normalized_question: Можно ли получить визу в Венгрию по приглашению от человека
    с венгерским ПМЖ?
  source_questions:
  - Можно ли получить визу в Венгрию по приглашению от человека с венгерским ПМЖ?
- normalized_question: Нужна ли виза D для въезда в Венгрию, если уже есть действующая
    французская мультивиза?
  source_questions:
  - Нужна ли виза D для въезда в Венгрию, если уже есть действующая французская мультивиза?
- normalized_question: Нужно ли получать разрешение полиции для въезда в Венгрию?
  source_questions:
  - Нужно ли получать разрешение полиции для въезда в Венгрию?
- normalized_question: Нужны ли прививка или ПЦР-тест для въезда в Венгрию?
  source_questions:
  - Нужны ли прививка или ПЦР-тест для въезда в Венгрию?
- normalized_question: Подойдет ли международная страховка от работы для визы в Венгрию?
  source_questions:
  - Подойдет ли международная страховка от работы (например, Cigna премиум) для визы
    в Венгрию?
- normalized_question: Можно ли использовать страховку из Беларуси для визы в Венгрию?
  source_questions:
  - Нужна ли страховка из Беларуси или нужно делать в Сербии?
- normalized_question: Как считать дату начала действия ВНЖ, если она не указана во
    вклейке?
  source_questions:
  - Как считать дату начала действия ВНЖ, если она не указана во вклейке?
- normalized_question: Как долго действует белый картон и нужно ли его обновлять?
  source_questions:
  - Как долго действует белый картон и нужно ли его обновлять?
- normalized_question: Что такое white card и как ее получить?
  source_questions:
  - Что такое white card и как ее получить?
  - Нужна ли долгосрочная аренда для White Card в Венгрии?
- normalized_question: Что такое читач с ВНЖ и где его получить?
  source_questions:
  - Что такое читач с ВНЖ и где его получить?
- normalized_question: Сколько стоят услуги помогаторов по оформлению визы?
  source_questions:
  - Сколько стоят услуги помогаторов по оформлению визы?
- normalized_question: Проверяют ли венгры, действительно ли ты живешь по указанному
    адресу при получении визы Digital Nomad?
  source_questions:
  - Проверяют ли венгры, действительно ли ты живешь по указанному адресу при получении
    визы Digital Nomad?
- normalized_question: Можно ли подать на ВНЖ в Венгрию по замороженному ИП без бизнес-счета?
  source_questions:
  - Можно ли подать на ВНЖ в Венгрию по замороженному ИП без бизнес-счета?
- normalized_question: Какие требования по доходу на ИП для получения венгерской визы?
  source_questions:
  - Какие требования по доходу на ИП для получения венгерской визы?
- normalized_question: Требуют ли венгры подтверждение пребывания в Венгрии после
    поездки?
  source_questions:
  - Требуют ли венгры подтверждение пребывания в Венгрии после поездки?
