category_slug: requirements
questions_text_md5: 93cf878d459acd3571996c56e6cd81d6
questions:
- normalized_question: Нужна ли зелёная карта (Green Card) для поездки на автомобиле
    с сербскими номерами в страны ЕС и какие страны её требуют?
  source_questions:
  - В какие страны из Сербии обязательно нужна зелёная карта (Green Card) для поездки
    на автомобиле?
  - Нужна ли зеленая карта (Green Card) для автомобиля на сербских номерах при поездке
    в страны ЕС?
  - Нужна ли зеленая карта для поездки в ЕС на автомобиле с сербской страховкой?
  - Нужна ли зелёная карта (Green Card) для поездки в Румынию на автомобиле с сербскими
    номерами?
  - Нужна ли страховка на авто с сербскими номерами при поездке в шенгенскую зону?
  - Нужна ли страховка на автомобиль для поездки в ЕС?
- normalized_question: Можно ли использовать российскую страховку (например, Тинькофф,
    Черехапа) для получения шенгенской визы и какие консульства её принимают?
  source_questions:
  - Какие консульства в Белграде принимают российскую страховку (Тинькофф или Черехапа)
    для оформления шенгенской визы?
  - Есть ли случаи отказов в приеме документов или в визе из-за русской страховки?
  - Можно ли использовать российскую туристическую страховку для получения шенгенской
    визы?
  - Подходит ли для шенгена в Белграде международная страховка от Тинькофф банка?
  - Подходит ли российская страховка (например, Тинькофф) для визы в Венгрию?
  - Подходит ли российская страховка для визы?
  - Примут ли во французском посольстве страховку от Тинькофф на год?
  - Принимают ли российские страховки (например, Т-Страхование) для въезда в страны
    ЕС?
  - Принимают ли российскую страховку Тинькофф при подаче на визу в Сербии?
  - Работают ли российские страховки (например, Тинькофф) для въезда в Шенген?
  - Подойдет ли страховка Тинькофф для подачи на болгарскую визу?
- normalized_question: Можно ли использовать сербскую медицинскую страховку (здравствену
    картицу/ОМС) вместо туристической страховки для поездки в Шенген и другие страны
    Европы?
  source_questions:
  - Действует ли сербская ОМС (медицинская страховка) в странах Европы, например в
    Венгрии? Нужно ли дополнительно оформлять туристическую страховку?
  - Действует ли сербский ОМС (обязательное медицинское страхование) как страховка
    для поездки в Испанию?
  - Можно ли использовать сербскую здравствену картицу (медицинскую карту) вместо
    туристической страховки для поездки в Шенген?
  - Подходит ли государственная страховка здоровья (для владельцев ВНЖ) для поездок
    в шенген?
  - Подходит ли обычное сербское здравственное страхование (zdravstveno osiguranje)
    в качестве туристической страховки для поездки в Хорватию?
  - Подходит ли сербская или черногорская медицинская страховка (ОМС) для подачи на
    визу в Испанию?
  - Подходит ли сербская страховка (типа ОМС) для получения визы Шенген?
- normalized_question: Подходит ли страховка Dunav для получения шенгенской визы?
  source_questions:
  - Можно ли использовать страховку Дунав для ВНЖ в Сербии для подачи на шенген?
  - Подойдет ли страховка Dunav для боравка (для получения ВНЖ) для подачи на шенгенскую
    визу?
  - Подходит ли страховка Дунав для венгерского шенгена?
  - Подходит ли страховка от Дунава и Поштанске (которую выдают при открытии бизнес-счета)
    для получения визы в Шенген?
- normalized_question: Обязательно ли включать покрытие COVID-19 в страховку для получения
    шенгенской визы?
  source_questions:
  - Какие посольства требуют явное указание COVID в страховке?
  - Можно ли исключать страховку от COVID-19 из полиса Dunav при подаче на Шенген?
  - Нужна ли страховка от пандемии для шенгенской визы при покупке полиса Дунав?
  - Нужно ли включать опцию Ковид при оформлении страховки Дунав для Шенгена?
  - Обязательно ли включать ковид в страховку для получения визы?
- normalized_question: Можно ли для получения мультивизы оформить страховку только
    на первую поездку или нужна страховка на весь период?
  source_questions:
  - Достаточно ли при подаче на многократную визу предоставить страховку только под
    первую поездку?
  - Можно ли для мультивизы делать страховку только на первый въезд, а затем для фактических
    въездов?
  - Какую страховку делать для получения мультивизы Шенген на полгода или год?
  - Какую страховку нужно делать для многократной шенгенской визы в Испанию и на какой
    срок?
- normalized_question: Подходит ли страховка от Raiffeisen Bank (Raif Premium/Uniqa)
    для получения шенгенской визы?
  source_questions:
  - Можно ли использовать страховку от Райффайзен банка Сербии для получения визы?
  - Подходит ли страховка Райффайзен банка (Raif Premium) для шенгенской визы?
  - Какие документы нужно прикладывать при подаче на шенген со страховкой Raiffeisen
    Premium (Uniqa)?
- normalized_question: Подходит ли страховка Grawe для получения шенгенской визы?
  source_questions:
  - Подходит ли страховка Grawe для Шенгена? Что покрывает тариф Породична (семейный)
    - можно ли оформить одну страховку на всю семью?
  - Подходит ли страховка Grawe для визы в Нидерланды?
  - Можно ли использовать семейную годовую страховку от Grawe для подачи на рабочую
    польскую визу (D)?
- normalized_question: Принимают ли семейную страховку для визы или нужна отдельная
    на каждого человека?
  source_questions:
  - В семейной страховке Generali с покрытием 40000 евро - это сумма на каждого человека
    или делится на всех? Примут ли такую страховку или лучше оформить отдельно на
    каждого?
  - Принимают ли семейную страховку или нужна отдельная на каждого человека?
  - Подходит ли семейная страховка Porodicno от Dunav для подачи на Шенген семьей
    из 4 человек?
  - Примут ли медицинскую страховку из пакета Райффайзен, где указано только имя держателя
    карты, но написано что члены семьи тоже застрахованы (без указания их имен), для
    визы мужа и дочки?
- normalized_question: Должен ли указываться номер паспорта в страховке и имеет ли
    это значение для визы и пограничников?
  source_questions:
  - Должен ли указываться номер паспорта в страховке и имеет ли это значение для пограничника?
  - Критично ли отсутствие номера паспорта в страховке для пограничников при первом
    въезде в Шенген (Швеция), если есть только фамилия, имя, номер полиса и персональный
    код страны ЕС?
- normalized_question: Можно ли использовать прошлогоднюю или годовую страховку повторно
    для новой визы, если не использованы все дни покрытия?
  source_questions:
  - Можно ли использовать прошлогоднюю страховку повторно, если пробыли меньше дней?
  - Если купить страховку Generali на год на 90 дней для визы в Испанию, можно ли
    использовать оставшиеся дни для следующей визы, если не пробыли все 90 дней в
    Евросоюзе?
- normalized_question: Можно ли получить длительную мультивизу (на полгода или год),
    если страховка оформлена только на 90 дней или на первую поездку?
  source_questions:
  - Можно ли получить годовую мультивизу, если страховка оформлена только на 90 дней?
  - Можно ли купить короткую страховку на 8 дней для получения мультивизы в Италию
    или обязательно нужна длинная страховка?
  - Нужно ли покупать страховку на больше чем 30 дней, чтобы получить визу на несколько
    месяцев?
- normalized_question: Подходит ли страховка от банка (бонусная к карте, например
    Mastercard Gold или Poštanska) для получения шенгенской визы?
  source_questions:
  - Подходит ли страховка от банка (которая идет бонусом к карте) для шенгенской визы?
  - Подходит ли страховка от Мастеркард Голд для визы?
  - Можно ли использовать карту Дунав (бонус при открытии бизнес-счета в Поштанске)
    в качестве страховки для подачи на Шенген?
  - Одобряют ли в посольстве Венгрии страховку от Поштански (которая идет с бизнес
    счетом) - достаточно ли копии пластиковой карты?
- normalized_question: Какие документы и страницы из страхового полиса нужно прикладывать
    при подаче на визу?
  source_questions:
  - Какие страницы из страхового полиса нужно прикладывать к документам для визы?
  - Что нужно распечатать из страхового полиса для посольства, если страховая компания
    прислала файл на 44 страницы (например, Generali)?
  - Нужно ли распечатывать страховку для подачи на визу?
  - Достаточно ли иметь на руках договор страховки путешественника, оформленной онлайн,
    или нужны какие-то ламинированные карточки?
- normalized_question: Подходит ли страховка Generali для получения шенгенской визы?
  source_questions:
  - Подойдет ли ДМС Generali в качестве страховки для получения шенгенских виз?
  - Принимают ли страховку Generali при подаче на визу? Нужно ли переводить её на
    английский? Нормально ли, что сумма покрытия не указана в полисе?
- normalized_question: Нужно ли для путешествий по ЕС на автомобиле с сербскими номерами
    дополнительно приобретать туристическую медицинскую страховку?
  source_questions:
  - Нужно ли для путешествий по ЕС на автомобиле с сербскими номерами и сербской страховкой
    дополнительно приобретать туристическую страховку?
  - Что такое 'путно осигуранье' для ребенка при выезде в Боснию и Хорватию, если
    есть сербская здравственна книжица?
